import { appendFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { join } from "node:path";

export interface ResumeState { task: string; sessionId?: string; currentChunk: number; status: "active" | "completed" | "blocked" | "failed"; nextStep: string; updatedAt: string; }
interface MemoryEntry { id: string; category: string; content: string; createdAt: string; }
interface MemoryDb { entries: MemoryEntry[]; resume?: ResumeState; }
export interface MemoryStore { ensureFile(): Promise<void>; read(): Promise<string>; appendDaily(entry: { did: string[]; decided: string[]; blocked: string[]; next: string }): Promise<void>; remember(category: string, content: string): Promise<void>; relevant(task: string, limit?: number): Promise<string[]>; saveResume(state: Omit<ResumeState, "updatedAt">): void; getResume(): ResumeState | undefined; close(): void; }
const MEMORY_TEMPLATE = `# Memory — IND\n\n## Project\n\n- **Goal:** Project-local memory for IND sessions.\n- **Where we are:** New project.\n\n## Standing decisions\n\n- Keep memory human-readable and append-only.\n`;
function terms(task: string): string[] { return [...new Set(task.toLowerCase().split(/[^a-z0-9_/-]+/).flatMap((part) => part.split(/[\/_-]+/)).filter((part) => part.length > 2))]; }
function readDb(path: string): MemoryDb { if (!existsSync(path)) return { entries: [] }; try { return JSON.parse(readFileSync(path, "utf8")) as MemoryDb; } catch { return { entries: [] }; } }
export function openMemoryStore(projectRoot: string): MemoryStore { const memoryPath = join(projectRoot, "MEMORY.md"); const directory = join(projectRoot, ".ind"); mkdirSync(directory, { recursive: true }); const dbPath = join(directory, "memory.json"); const db = readDb(dbPath); const save = () => writeFileSync(dbPath, JSON.stringify(db, null, 2), "utf8"); return { async ensureFile() { await mkdir(projectRoot, { recursive: true }); if (!existsSync(memoryPath)) await writeFile(memoryPath, MEMORY_TEMPLATE, "utf8"); }, async read() { await this.ensureFile(); return readFile(memoryPath, "utf8"); }, async appendDaily(entry) { await this.ensureFile(); const lines = [`\n---\n\n## ${new Date().toISOString().slice(0, 10)}`, "", "- **Did:**", ...entry.did.map((item) => `  - ${item}`), "- **Decided:**", ...entry.decided.map((item) => `  - ${item}`), "- **Blocked:**", ...entry.blocked.map((item) => `  - ${item}`), `- **Next:** ${entry.next}`, ""]; await appendFile(memoryPath, `${lines.join("\n")}\n`, "utf8"); for (const content of [...entry.did, ...entry.decided, ...entry.blocked, entry.next]) db.entries.push({ id: randomUUID(), category: "session", content, createdAt: new Date().toISOString() }); save(); }, async remember(category, content) { await this.ensureFile(); await appendFile(memoryPath, `\n- **${category}:** ${content}\n`, "utf8"); db.entries.push({ id: randomUUID(), category, content, createdAt: new Date().toISOString() }); save(); }, async relevant(task, limit = 8) { const content = await this.read(); const taskTerms = terms(task); return content.split(/\r?\n/).filter((line) => line.trim().startsWith("-") || line.startsWith("## ")).filter((line) => taskTerms.length === 0 || taskTerms.some((term) => line.toLowerCase().includes(term))).slice(-limit); }, saveResume(state) { db.resume = { ...state, updatedAt: new Date().toISOString() }; save(); }, getResume() { return db.resume; }, close() {} }; }
